# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 18 Aug 2014 18:11:52 +0000
*               @ALL          1
*               @user         8
